INFO:root:model_name: /groups/4/gcb50389/pretrained/llama2-HF/Llama-2-7b-hf
INFO:root:load tokenizer
Using pad_token, but it is not set yet.
INFO:root:set pad_token to </s>
INFO:root:load model: {'pretrained_model_name_or_path': '/groups/4/gcb50389/pretrained/llama2-HF/Llama-2-7b-hf', 'device_map': 'auto', 'trust_remote_code': True}
INFO:torch.distributed.nn.jit.instantiator:Created a temporary directory at /tmp/40877216.1.gpu/tmp_93q9wxc
INFO:torch.distributed.nn.jit.instantiator:Writing /tmp/40877216.1.gpu/tmp_93q9wxc/_remote_module_non_scriptable.py
[2023-11-01 21:07:50,154] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]Loading checkpoint shards:  50%|█████     | 1/2 [09:36<09:36, 576.85s/it]Loading checkpoint shards: 100%|██████████| 2/2 [10:55<00:00, 283.85s/it]Loading checkpoint shards: 100%|██████████| 2/2 [10:55<00:00, 327.80s/it]
INFO:root:processing R1 data.
Downloading and preparing dataset json/default to file:///scratch/acf15802az/.cache/huggingface/datasets/json/default-73b2034119f5975d/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4...
Downloading data files:   0%|          | 0/1 [00:00<?, ?it/s]Downloading data files: 100%|██████████| 1/1 [00:00<00:00, 2522.13it/s]
Extracting data files:   0%|          | 0/1 [00:00<?, ?it/s]Extracting data files: 100%|██████████| 1/1 [00:00<00:00, 199.20it/s]
Generating train split: 0 examples [00:00, ? examples/s]                                                        Dataset json downloaded and prepared to file:///scratch/acf15802az/.cache/huggingface/datasets/json/default-73b2034119f5975d/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4. Subsequent calls will reuse this data.
Traceback (most recent call last):
  File "/home/acf15802az/abci-examples/202307/src/generate_texts_llama_jplaw_v03.py", line 108, in <module>
    fire.Fire(main)
  File "/home/acf15802az/abci-examples/202307/.venv/lib/python3.11/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/acf15802az/abci-examples/202307/.venv/lib/python3.11/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/acf15802az/abci-examples/202307/.venv/lib/python3.11/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/acf15802az/abci-examples/202307/src/generate_texts_llama_jplaw_v03.py", line 87, in main
    dataset = load_dataset(test_file=config["data"][f"test_file{j}"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/acf15802az/abci-examples/202307/src/generate_texts_llama_jplaw_v03.py", line 21, in load_dataset
    return datasets.load_dataset("json", data_files=test_file, split="train")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/acf15802az/abci-examples/202307/.venv/lib/python3.11/site-packages/datasets/load.py", line 1810, in load_dataset
    ds = builder_instance.as_dataset(split=split, verification_mode=verification_mode, in_memory=keep_in_memory)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/acf15802az/abci-examples/202307/.venv/lib/python3.11/site-packages/datasets/builder.py", line 1107, in as_dataset
    raise NotImplementedError(f"Loading a dataset cached in a {type(self._fs).__name__} is not supported.")
NotImplementedError: Loading a dataset cached in a LocalFileSystem is not supported.
