INFO:root:model_name: /groups/4/gcb50389/pretrained/llama2-HF/Llama-2-7b-hf
INFO:root:load tokenizer
Using pad_token, but it is not set yet.
INFO:root:set pad_token to </s>
INFO:root:load model: {'pretrained_model_name_or_path': '/groups/4/gcb50389/pretrained/llama2-HF/Llama-2-7b-hf', 'device_map': 'auto', 'trust_remote_code': True}
INFO:torch.distributed.nn.jit.instantiator:Created a temporary directory at /tmp/40877265.1.gpu/tmpsl6li6y4
INFO:torch.distributed.nn.jit.instantiator:Writing /tmp/40877265.1.gpu/tmpsl6li6y4/_remote_module_non_scriptable.py
[2023-11-01 21:26:28,675] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]Loading checkpoint shards:  50%|█████     | 1/2 [08:23<08:23, 503.05s/it]Loading checkpoint shards: 100%|██████████| 2/2 [09:41<00:00, 253.46s/it]Loading checkpoint shards: 100%|██████████| 2/2 [09:41<00:00, 290.90s/it]
INFO:root:processing R1 data.
WARNING:datasets.builder:Found cached dataset json (/scratch/acf15802az/.cache/huggingface/datasets/json/default-73b2034119f5975d/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4)
INFO:root:processing 20th data.
Traceback (most recent call last):
  File "/home/acf15802az/abci-examples/202307/src/generate_texts_llama_jplaw_v03.py", line 108, in <module>
    fire.Fire(main)
  File "/home/acf15802az/abci-examples/202307/.venv/lib/python3.11/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/acf15802az/abci-examples/202307/.venv/lib/python3.11/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/acf15802az/abci-examples/202307/.venv/lib/python3.11/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/acf15802az/abci-examples/202307/src/generate_texts_llama_jplaw_v03.py", line 97, in main
    year = data["year"]
           ~~~~^^^^^^^^
KeyError: 'year'
